fix: prevent possible overflow
kstenerud/KSCrash pull request #430
Opened 2022-06-10 15:08 UTC by armcknight

The main fix is for a possible overflow when performing a multiplication in some pointer arithmetic.

There are a few unrelated changes rolled in, I'm happy to break them out if desired.

2023-01-06 14:07 UTC, bamx23 commented
Hey @armcknight, could you reopen this PR? I'm planning to land some of the latest fixes and make a release.

2023-02-07 19:09 UTC, armcknight commented
Sure thing @bamx23!

2023-02-10 19:24 UTC, bamx23 requested changes

2023-02-10 19:24 UTC, bamx23 commented on Source/KSCrash/Recording/Tools/KSObjC.c
> +    const struct ivar_t *ivar = (void *)(ivarPtr + (uintptr_t)ivars->entsizeAndFlags * (uintptr_t)ivarIndex);
May I ask you to preserve project code style?
```suggestion
    const struct ivar_t* ivar = (void*)(ivarPtr + (uintptr_t)ivars->entsizeAndFlags * (uintptr_t)ivarIndex);
```

2023-02-10 19:24 UTC, bamx23 commented on Source/KSCrash/Recording/Monitors/KSCrashMonitor_Signal.c
> -    // This is technically not allowed, but it works in OSX and iOS.
Why this line was removed?

2023-02-14 08:43 UTC, bamx23 commented on Source/KSCrash/Recording/Monitors/KSCrashMonitor_Signal.c
> -    // This is technically not allowed, but it works in OSX and iOS.
Thank for clarification!

2023-02-14 08:43 UTC, bamx23 approved these changes

2023-02-14 08:43 UTC, merged

2023-02-14 18:52 UTC, armcknight commented on Source/KSCrash/Recording/Monitors/KSCrashMonitor_Signal.c
> -    // This is technically not allowed, but it works in OSX and iOS.
My pleasure!