Fix tail call optimisation in C++ backtrace capture
kstenerud/KSCrash pull request #468
Opened 2024-05-04 12:33 UTC by bamx23

According to [documentation]
(https://releases.llvm.org/15.0.0/tools/clang/docs/AttributeReference.html#disable-tail-calls) there's a `__attribute__((disable_tail_calls))` attribute that should work fine for our case where we need to make sure the stacktrace has predictable number of calls at the top.

2024-05-04 13:25 UTC, GLinnik21 requested changes
It looks great! But I would make sure that this attribute is not ignored and the frames really remain.

2024-05-09 21:14 UTC, naftaly commented
fwiw, `__asm__ __volatile__("");` should also force no tail call optimization.

2024-05-09 21:35 UTC, GLinnik21 commented
> fwiw, `__asm__ __volatile__("");` should also force no tail call optimization.

The question is which of these codes is more portable across different compilers?

2024-05-09 21:44 UTC, naftaly commented
definitely the attribute if it works.

> `__asm__ __volatile__("");`

Hard to say really. I'd expect an attribute like that to be my first choice, but the code I shared is what I found [Apple does/was-doing in CF](https://github.com/apple/swift-corelibs-foundation/blob/main/CoreFoundation/RunLoop.subproj/CFRunLoop.c#L2001).

2024-05-18 13:58 UTC, bamx23 commented
I really like the idea with `__asm__ __volatile__("");`. Having both this and the attribute should not harm. Thanks @naftaly!

2024-05-23 11:41 UTC, bamx23 commented
Tested this PR:
|  | Static Lib | Dynamic Lib |
| --- | --- | --- |
| Before | <img width="700" alt="Screenshot 2024-05-23 at 12 33 18" src="https://github.com/kstenerud/KSCrash/assets/443972/99f2fa58-6958-4a3f-ab4e-e50cd27c23a2"> | <img width="700" alt="Screenshot 2024-05-23 at 12 32 41" src="https://github.com/kstenerud/KSCrash/assets/443972/7d78f9a0-57ba-4269-9c78-341c1aca4cec"> |
| After | <img width="700" alt="Screenshot 2024-05-23 at 12 34 30" src="https://github.com/kstenerud/KSCrash/assets/443972/5b37567c-1370-410b-a27a-95329d2dc115"> | <img width="700" alt="Screenshot 2024-05-23 at 12 34 01" src="https://github.com/kstenerud/KSCrash/assets/443972/a7e04335-f96f-4cec-a0af-c1653623a3dd"> |

See that after the fix there's an extra frame in the stacktrace.
cc @GLinnik21

2024-05-23 12:00 UTC, GLinnik21 commented
So this extra frame had been deleted prior to fix, right?

2024-05-23 12:12 UTC, bamx23 commented
> > See that after the fix there's an extra frame in the stacktrace.
> > cc @GLinnik21
> 
> Did the frame always get deleted before this fix?

Yes (with Release build)

2024-05-23 12:30 UTC, GLinnik21 approved these changes
Great! Thank you very much!

2024-05-23 14:33 UTC, merged