FIX: Resolve stack overflow caused by insufficient disk space.
kstenerud/KSCrash pull request #479
Opened 2024-05-17 07:33 UTC by xuezhulian

When the disk space is insufficient, the ksfu_flushBufferedWriter method will return false, and the value of writer->position will not be set to 0. Continuing to write values to writer->buffer at this point will result in a stack overflow.

2024-05-17 14:06 UTC, GLinnik21 requested changes
Thanks for the fix! Just to clarify, did you mean buffer overflow instead of stack overflow? The issue seems related to the buffer exceeding its capacity if `ksfu_flushBufferedWriter` fails.

2024-05-18 00:46 UTC, xuezhulian commented
@GLinnik21 writer->buffer is a variable allocated on the stack, so it causes a stack overflow.
`char writeBuffer[1024];`

2024-05-20 14:39 UTC, GLinnik21 commented
Let’s add some unit tests. If it’s too complex without mocks or dependency injection, we can merge it as is.

2024-05-21 06:52 UTC, xuezhulian commented
Sorry, writing unit tests is quite challenging for me.😞

2024-05-21 09:23 UTC, merged