refactor: optimizing the logic for retrieving free memory on iOS 13+
kstenerud/KSCrash pull request #552
Opened 2024-09-03 06:42 UTC by 94haox

In iOS 13 and later, Apple has provided an API to obtain available memory.
link: https://developer.apple.com/documentation/os/3191911-os_proc_available_memory

2024-09-03 09:33 UTC, GLinnik21 requested changes
As far as I can understand, while `os_proc_available_memory()` is a more accurate measure for app-specific available memory, it represents a fundamentally different value than the VM stats approach:

1. Different metric: `os_proc_available_memory()` shows memory available to the process, while VM stats show system-wide free memory. These are not directly comparable.

2. Inconsistent reporting: Using `os_proc_available_memory()` for iOS 13+ and VM stats for earlier versions would create a discontinuity in reported values across iOS versions, potentially confusing users of the crash reporting system.

What do you think?

2024-09-03 09:42 UTC, 94haox commented on Sources/KSCrashRecording/Monitors/KSCrashMonitor_System.m
> +#if ASTROLABECRASH_HOST_IOS
Sorry, this macro is the version I forked. I will correct it in the next commit.

2024-09-03 10:03 UTC, 94haox commented
> As far as I can understand, while `os_proc_available_memory()` is a more accurate measure for app-specific available memory, it represents a fundamentally different value than the VM stats approach:
> 
> 1. Different metric: `os_proc_available_memory()` shows memory available to the process, while VM stats show system-wide free memory. These are not directly comparable.
> 2. Inconsistent reporting: Using `os_proc_available_memory()` for iOS 13+ and VM stats for earlier versions would create a discontinuity in reported values across iOS versions, potentially confusing users of the crash reporting system.
> 
> What do you think?

I believe your points are valid, but I have a different opinion:

Metric Standards: From the perspective of solving problems, for systems like iOS/tvOS/watchOS that only support single-process apps, the idle memory at the process level is more valuable compared to the system level idle memory (I guess this is also the reason why the API does not support macOS?);

Inconsistency in Reporting: Indeed, such problems may exist, but the current logic, I guess, is a compromise strategy when precise process memory information cannot be obtained (I'm not quite sure)? Compared to accurate information, the priority of report value continuity should be relatively low?

2024-09-03 10:25 UTC, GLinnik21 commented
Thanks for your perspective. The recent implementation in KSCrash seems to address our concerns effectively. You might want to check out these files for more details:

https://github.com/kstenerud/KSCrash/blob/962934327eb42ebee883eca7258df1fd03e2cf89/Sources/KSCrashRecording/KSCrashAppMemoryTracker.m
https://github.com/kstenerud/KSCrash/blob/962934327eb42ebee883eca7258df1fd03e2cf89/Sources/KSCrashRecording/KSCrashAppMemory.m

What do you think about this approach?

2024-09-04 11:16 UTC, 94haox commented
That's great, the feature you mentioned is very useful. It seems I haven't been paying attention to KSCrash for quite a while 😄.

2024-09-04 11:16 UTC, closed without merging